### PR TITLE
Update proxy-https-to-https.conf

### PR DESCRIPTION
**Pull request by alirasol**
This is what worked for me... Otherwise I got stuck in a loop of hell

### CODE REVIEW

**Comment by agolybev** [comment]
Hi @alirasol, your changes break test.

**Comment by alirasol** [comment]
@agolybev my changes were meant for me actually. To save them in case I need it in the future.
I have a complicated setup on my server, and it the original file affected other services on the server.

**Comment by ShockwaveNN** [comment]
> @agolybev my changes were meant for me actually. To save them in case I need it in the future.

If your changes meant only for you - you should fork repo, not to create PullRequest

**Comment by alirasol** [comment]
Sorry about that. I am not a github pro.

**Pull request closed without merging**
