### PR TITLE
Removing trailing / for proxypass

### PR DESCRIPTION
**Pull request by FriedCircuits**
I had to remove the trailing slash for proxy to virtual path to work.

### CODE REVIEW

**Comment by agolybev** [comment]
Hi @FriedCircuits, it doesn't work while "virtual path" proxying only?

**Comment by FriedCircuits** [comment]
I was getting cannot get //welcome in the browser test. Once I removed the / it worked.

**Comment by agolybev** [comment]
@FriedCircuits, It seem no difference in my case.  I use apache v2.4.23, which apache version do you use?

**Comment by FriedCircuits** [comment]
I am on Server version: Apache/2.4.18 (Ubuntu)

**Pull request merged**
